Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Nginx Reverse Proxy
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
  # Jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 8888, id: "jenkins"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
