Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.hostname = "dras-dev"

  # Nginx Reverse Proxy
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"

  # Jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 8888, id: "jenkins"

  config.vm.provider "libvirt" do |lv|
    lv.memory = 4096
    lv.cpus = 2
  end

  config.vm.provision "shell", path: "bootstrap.sh"
end
